#spring:
#  application:
#    name: auth-service
#  jpa:
#    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddlAuto: update
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/shop_iphone?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
#    username: root
#    password: admin123
#server:
#  port: 3001
#  servlet:
#    contextPath:
#
#eureka:
#  client:
#  serviceUrl:
#    defaultZone: http://localhost:8888/eureka/
#
#security:
#  oauth2:
#    client:
#      clientId: client
#      clientSecret: client@2022
#      accessTokenValiditySeconds: 900
#      refreshTokenValiditySeconds: 18000
#encrypt:
#  keyStore:
#    alias: jwt
#    password: god@123
