security:
  oauth2:
      resource:
        userInfoUri: http://localhost:3001/auth/user

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user-service
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddlAuto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop_iphone?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: admin
server:
  port: 3002

eureka:
  client:
  serviceUrl:
    defaultZone: http://localhost:8888/eureka/


